// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zctpvjfrbstoftxjowfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdHB2amZyYnN0b2Z0eGpvd2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjI0ODMsImV4cCI6MjA2NzAzODQ4M30.5HgTLEmkGLPx-hB82tB94fIIqANFoZvHAcGr8u3CGTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});